

name: Run Postman Tests
on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install newman
        run: npm install -g newman

      - name: Install dependencies
        run: npm install

      - name: Install reporter
        run: npm install -g allure-commandline

      - name: Run POSTMAN collection
        run: npm run test

      - name: Generate Report
        if: always()
        run: npm run allure:report # Name of the allure generate script
      - name: Upload Results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: allure-results
          path: ./allure-results # Name of the folder with allure results                    
      - name: Publishing Allure artifact to Github Actions
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure-report
          path: allure-report       
      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: always()
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: allure-report # The folder the action should deploy.t